### PR TITLE
Electron publish

### PR DESCRIPTION
**Pull request by campersau**
based on #1240 this will create a `dist` folder which contains all zipped builds from electron.
These zips are uploaded as artifacts on AppVeyor for every build and can be release by Travis if a commit in the `master` branch is tagged.

Maybe we want to automatically create tags during builds on master which then starts another build which creates the actual release.

fixes https://github.com/FredrikNoren/ungit/issues/1218
fixes https://github.com/FredrikNoren/ungit/issues/1222

### CODE REVIEW

**Comment by Hirse** [comment]
Is this deploying on every build or only when the version has increased?

**Comment by campersau** [comment]
@Hirse both. The electron packages will be available on every build as artifacts on AppVeyor (they keep them for 6 months).
If a commit gets tagged in master then this would produce a GitHub release with all electron packages as artifacts.
See https://github.com/FredrikNoren/ungit/issues/1218#issuecomment-548980020 for examples.

**Comment by campersau** [comment]
In the second commit I also enabled automatic version tagging.
Here are the different scenarios:

- PR **with** or **without** `package.json` version change
  1. Build runs on travis and appveyor.
  2. Electron packages are uploaded as artifacts on appveyor.

- Commit to master (directly or PR merge) **without** `package.json` version change
  1. Build runs on travis and appveyor.
  2. Electron packages are uploaded as artifacts on appveyor.
  3. Travis tries to publish npm package and fails.

- Commit to master (directly or PR merge) **with** `package.json` version change
  1. Build runs on travis and appveyor.
  2. Electron packages are uploaded as artifacts on appveyor.
  3. Travis publishes npm package.
  4. Travis creates a new tag with the updated version number,
  5. The new tag triggers new builds on travis and appveyor.
  6. Electron packages are uploaded as artifacts on appveyor.
  7. Travis deploys a new release on github including electron packages.

Some notes:
- The deployment of the release and the tag creation are currently using my (`campersau`) GitHub token. So I guess the releases would always be release with my user.
- We could provide a bit more details in the release description (body). Maybe we can link to the [CHANGELOG.md](https://github.com/FredrikNoren/ungit/blob/master/CHANGELOG.md)?

Example: https://github.com/campersau/ungit/releases/tag/1.4.48

cc @jung-kim @FredrikNoren

**Comment by Hirse** [comment]
The current CHANGELOG would only allow linking to the whole file.
For linking to specific versions, which would be nicer, the format would have to be slightly changed. I would propose adopting this one: https://keepachangelog.com

**Comment by campersau** [comment]
@Hirse Yes, that's how it was done before the automatic version updates were introduced.
See https://github.com/FredrikNoren/ungit/issues/687#issuecomment-178632834

I have updated the change log to use the https://keepachangelog.com format and also applied all missing tags. (I used `git log -m --first-parent -L5,5:package.json` to get all the commits and wrote a program for reading the package json on each of the commits and tagging it.)

**Comment by Hirse** [comment]
@campersau I noticed the old format after writing my comment. Looks good after transforming it, though some changes might fit better under a "Changed" headline rather than "Fixed".

**Comment by campersau** [comment]
@Hirse Yeah, maybe. I just selected all and went with "Fixed" as default and pnly changed it to "Added" sometimes.

**Comment by campersau** [comment]
There is also [electron-builder](https://github.com/electron-userland/electron-builder) which can build e.g. portable executables with auto update functionality. Which would make this scenario even easier. But let's see first how much demand there is for that after this PR is merged or should we move now?

(Example project which uses it: https://github.com/mifi/lossless-cut/releases)

**Comment by campersau** [comment]
The macOS electron packages created by appveyor (windows) for each build don't work because of serveral symlink issues on windows. (https://github.com/electron/electron-packager/pull/984#issuecomment-556994986)
The release packages which are build on travis (linux) do work.

**Pull request merged**
