### PR TITLE
[#847] Fix case sensitivity of email address in gravatar hash

### LINKED ISSUE #847: Avatar is not always shown even though Gravatar avatar is present

### PR DESCRIPTION
**Pull request by Thatkookooguy**
- Solve vase sensitivity for gravatar avatars [resolves #847]
> based on https://en.gravatar.com/site/implement/hash/
> Currently, if I write `Neilkalman@gmail.com` or `neilkalman@gmail.com`, I don't get the same result. I made it so that every email is transformed to lowercase so that md5 will work

### CODE REVIEW

**Comment by Thatkookooguy** [comment]
I'm not sure if I wrote the `CHANGELOG.MD` part in the right format. If not, tell me and I'll fix it :-)

thanks!

**Comment by FredrikNoren** [comment]
Nice! Almost right with the changelog, this is how it should look:

```md
- 1.0.1: [patch] Fixed gravatar avatar fetch if email have different cases applied. [#847](https://github.com/FredrikNoren/ungit/issues/847)
- 1.0.0: Introduced Continuous delivery. [#823](https://github.com/FredrikNoren/ungit/issues/823)
```

(I.e. just adding a row above the 1.0.0 row)

**Comment by Thatkookooguy** [comment]
@FredrikNoren changed the `CHANGELOG.MD` file as you requested 😄 

thanks!

**Comment by Thatkookooguy** [comment]
@FredrikNoren all the tests passed on my local machine. Can you please re-run the tests on `appveyor` and `travis`?

**Comment by codingtwinky** [comment]
I've been noticing several phantomjs failed errors with latest phantomjs, which is unfortunate and hopefully they will fix it soon.

Not sure how to retrigger windows test but I have more fixes to stabilize tests coming and hopefully that fixes.  But rest looks good though!

Thanks!!

**Comment by Thatkookooguy** [comment]
@codingtwinky are you talking about my addition? because I thought about doing another PR to add the default hash gravatar they generate for users without an avatar.

should I put it somewhere else in order to not `cause some over head when many nodes are loaded`?

**Comment by codingtwinky** [comment]
Ah, let me clarify.  what I meant is that `this.authorGravatar = ko.computed(function() {...` doesn't have to be `ko.computed` and many other variables often don't need to be `ko.computed` or `ko.observable`.  For this case, `authorGravatar` will not change once it is calculated at initialization.

I was just mentioning a larger code clean up effort that I would like to do.

**Comment by Thatkookooguy** [comment]
@codingtwinky oh cool :-)

**Pull request merged**
