### PR TITLE
Empty commits

### LINKED ISSUE #1028: Add button for empty-commits
Useful for triggering CI

### PR DESCRIPTION
**Pull request by ylecuyer**
Allows empty commit from the staging view interface
fixes #1028

### CODE REVIEW

**Comment by ylecuyer** [comment]
@jung-kim I don't understand why the build fail. The test I added is green.
Is there a flappy spec ?

**Comment by campersau** [comment]
Maybe also call `this.emptyCommit(false);` here
https://github.com/FredrikNoren/ungit/blob/42b4b0f904e08c32f53c0960f1e08d196aff33bf/components/staging/staging.js#L216-L227

---

`--allow-empty` is also needed if you amend an empty commit.

**Comment by jung-kim** [comment]
Right, feel free to run `grunt clicktest` to run all tests.  Also there is `grunt `clickParallel` for parallel testing if you want to speed it up

**Comment by ylecuyer** [comment]
I updated the PR with @campersau hints

**Comment by jung-kim** [comment]
Thanks!

**Pull request merged**
