### PR TITLE
fix to many file change events from file system watchers

### LINKED ISSUE #820: Endless status requests since #809 on windows
With the new feature from #809 ungit makes endless status requests on windows even though nothing has changed.
Will investigate further over the weekend.

image

image

/cc @codingtwinky

### PR DESCRIPTION
**Pull request by campersau**
fixes #820 

There might be an other bug:
What if `.gitignore` changes? Should we also update the state on the server?
<sub><strike>(currently changes to to `.gitignore` file are ignored because of the `startsWith` check)</strike> also fixed with this PR</sub>

### CODE REVIEW

**Comment by codingtwinky** [comment]
@campersau is there anything I can do to help you to get the tests passed in travis?  I think file watcher may not be working as intended in linux env.

**Comment by campersau** [comment]
@codingtwinky Yes, I have currently no idea why it does not work on linux (always getting timeouts). I pushed some tests but linux never worked. Windows works from time to time.

**Comment by codingtwinky** [comment]
It seems that problem was mis configured file watch path. I guess over active file watch trigger existed in unix OSs as well and it helped pass during the unix test.  Once you fixed it, tests start failing as it was previously relied on incorrectly triggered events.  

Now the path is corrected we should be good I think.  Let me know how you think @campersau

**Comment by campersau** [comment]
@codingtwinky wow thank you! Yes that seems to be the solution 👍

**Pull request merged**
