### PR TITLE
use child_process.exec for windows

### LINKED ISSUE #559: credentials helper does not work correctly
With the latest version of ungit the credentials helper in ungit does not show up in the browser. Instead I have to insert my credentials inside the command prompt.

Here is an example output:
```
2015-05-26T15:37:40.375Z - info: git executing: P:\ungit -c color.ui=false -c core.quotepath=false -c core.pager=cat -c credential.helper="P:/ungit/bin/credentials-helper 0 8448" fetch origin --prune

Password for 'https://campersau@github.com':
```

Maybe it is also related to the `child_process.spawn` change?

Windows 8.1 x64
Node v0.12.3
Git 1.8.3.msysgit.0

### PR DESCRIPTION
**Pull request by campersau**
I know this is sad but I could not find any other way to fix the issues with `child_process.spawn` on windows...
This fixed #559 for me.

Please test this fix on other OSes too.

### CODE REVIEW

**Comment by Ajedi32** [comment]
If you couldn't get `child_process.spawn` to work correctly on Windows, perhaps you might want to put together a reproducible example and submit a bug report to [joyent/node](https://github.com/joyent/node).

In the mean time this seems like an acceptable fix to, provided it doesn't introduce any regressions. For example, one of the reasons we switched to `child_process.spawn` in the first place was to fix #486. Does this patch re-introduce that problem?

**Comment by campersau** [comment]
@Ajedi32 here is an example for this bug: https://github.com/FredrikNoren/ungit/issues/541#issuecomment-105544642
Sadly it does re-introduce the problem on windows...

**Comment by Ajedi32** [comment]
Cool. You want to open an issue for that on [joyent/node](https://github.com/joyent/node)? I'd do it myself, but I'm not nearly as familiar with the problem as you are, and I have limited experience working with node. (You can reference the issue in this repository from the created issue on node's repo as `FredrikNoren/ungit#541`.)

**Comment by campersau** [comment]
Since I found the real bug for #541 (see #563) I will close this PR and try to find another way to fix #559 .

**Comment by codingtwinky** [comment]
Hmm...  This is a lovely bug...  Thanks

**Pull request closed without merging**
