### PR TITLE
Allow Ungit to functional under sub dir of a git dir

### LINKED ISSUE #734: viewing a commit's file changes is broken
When I click on a previous commit bubble, I am able to see a list of files that were changed as well as the number of lines changed in each file. However, when I click on a file, I am unable to see the actual changes made to that file, although I can see the UI twitch on click and `Event: Object {event: "graph-render"}` appears in the JS console.

ungit@0.10.1

### PR DESCRIPTION
**Pull request by codingtwinky**
Allows operation at a sub dir of git dir.

i.e. if there is a git directory `/tmp/test`, navigating to any sub dir under `/tmp/test` in ungit should be functional as if one is at `/tmp/test`.

I think this will fix #734 but I'm too lazy to test it... :P maybe I will do it over the weekends... :D

### CODE REVIEW

**Comment by codingtwinky** [comment]
In my testing this fixes #734.

Merging.

**Comment by campersau** [comment]
This breaks a test in windows. You can see it here: https://ci.appveyor.com/project/FredrikNoren/ungit/build/1.0.224#L1821 (line 1821)

It also automatically changes `\` to `/` in the path input. Which is bad on windows because we don't get autocompletion. Also I am now unable to navigate to a git subdirectory. For example it automatically redirects from `P:\ungit\components` to `P:/ungit` or was this intended?
image

**Comment by codingtwinky** [comment]
is navigation to sub directory of a git directory a valid use case? I'm not sure if it is.    

Right I see that windows test are unhapy and it will need more thought.

**Comment by campersau** [comment]
I am also not sure. Navigating to submodules works. Just wanted to know if this was intended :smiley:

**Comment by codingtwinky** [comment]
Hooray! unless objections arises, I don't think navigation to sub dir of a git dir is a valid use case thus such action will result in redirection to git root dir.

If I can't come up with a valid fix for windows I will back out this merge before tonight

**Pull request merged**
