### PR TITLE
Debug appveyor

### PR DESCRIPTION
**Pull request by ylecuyer**
Attemp to debug appveyor with: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

### CODE REVIEW

**Comment by ylecuyer** [comment]
img_20180210_220902
Couldn't take a better screenshot. It gets stuck here, the abort button isn't clicked automatically. If clicked manually tests continue

**Comment by jung-kim** [comment]
So the idea of checking in "password" field to the git repos is not an encouraging thought.  

Are you sure you are not exposing yourself or any of your groups by sharing RDP password?

**Comment by ylecuyer** [comment]
It's not a big deal. The password only works for one 1 hour max while a build from this branch is running.

**Comment by ylecuyer** [comment]
Closed #1047

**Pull request closed without merging**
