### PR TITLE
Change commit ordering to date-order.

### LINKED ISSUE #641: Branch several commits behind master is filtered out
If you have a feature branch that's a bit behind master, the commits will be filtered out even if you currently have the branch checked out. Screenshot to demonstrate:

bug

### PR DESCRIPTION
**Pull request by keiter**
Fixes #641

### CODE REVIEW

**Comment by keiter** [comment]
Do you guys have a strong opinion on `topo-order` vs. `date-order` as a nonoptional default? I'd be fine with a configurable option as well, but `topo-order` really only barely works in our workflow as described in the issue.

**Comment by codingtwinky** [comment]
I personally don't see huge issues with this.  However, order of nodes are important on how we color and displayed.  So may need more burn time.  

have you noticed any other side effects?  I'd imagine it be fine and will test on my own later.

**Comment by keiter** [comment]
I'm using the patched version at work, and it appears to work well thus far. Coloring is working as it did previously AFAIK. The difference is mostly in the layout of the graph, as the graph nodes are laid out in order of commit date you can get them "interleaved" when there is paralell work going on. Screenshot:

date-order

**Comment by codingtwinky** [comment]
It looks good to me and I think it makes more sense.

**Comment by nicolaiskogheim** [comment]
This looks really neat. :+1:

**Pull request merged**
