### PR TITLE
Fix for favorites linking in case of rootPath option is used

### PR DESCRIPTION
**Pull request by exsilium**
As reported on May 11th by @sebastianmay for rootPath feature issue #609 I just recently hit that one as well and I hope this will get pulled to the next version. Thanks and Cheers!

:beers:

### CODE REVIEW

**Comment by codingtwinky** [comment]
:+1:

But if you could write a click test for it I will give you a virtual highfive...

**Comment by exsilium** [comment]
No problem, I'll take a look :)

**Comment by codingtwinky** [comment]
Feel free to add tests later!

**Comment by exsilium** [comment]
Thanks, still in progress... I was strayed from the path for a while without realizing that the `~/.ungitrc` interferes with the test suite :feelsgood:

**Comment by viharm** [comment]
This issue also occurs on links to parent repository when viewing submodules.

**Pull request merged**
