### PR TITLE
Add clipboard button on commit

### PR DESCRIPTION
**Pull request by wmertens**
Right now, it shows when you hover or click the commit. How can I make it also show when I just hover over the commit hash?

Should this have a test? What should it test?

### CODE REVIEW

**Comment by campersau** [comment]
Please note that `navigator.clipboard.writeText` will only work on `localhost` and `https` sites. Since ungit can bind to other hostnames as well (or all `0.0.0.0`) this would not work in these cases.

> [Note that the API only works when served over secured domains (https) or localhost and when the page is the browser's currently active tab.](https://alligator.io/js/async-clipboard-api/)

https://web.dev/async-clipboard/#security-and-permissions

See also https://stackoverflow.com/a/30810322 for possible workarounds.
You can test this scenario by setting `ungitBindIp` to `0.0.0.0` and then load ungit with `http://[yourcomputername]:8448`

---

ungit uses octicon icons everywhere else so I think it would be better to use them here too. E.g. https://primer.style/octicons/clippy-16

---

What do you think about making the button smaller like `btn-xs`?

**Comment by wmertens** [comment]
@campersau actually I'm a complete n00b at KO and I'm working on the nodegit branch, this was a quick hack to get a feel for it. If you were to implement your suggestions I'd be really grateful :sweat_smile: (if not, I totally understand, I'm just saying that I wouldn't feel offended in the least if you implemented this properly, on the contrary)

**Comment by campersau** [comment]
@wmertens  How do you like that?
image

Ref: https://github.com/FredrikNoren/ungit/issues/108

**Comment by wmertens** [comment]
@campersau :100: :heart_eyes:

**Comment by wmertens** [comment]
I just wonder how to show the button when you hover over the commit message, not the commit node. That way you can quickly copy an oid from the page.

**Comment by campersau** [comment]
Or just keep the button always visible regardless of mouseover?

**Comment by wmertens** [comment]
Hmm right, I was worrying that it adds too much visual noise

**Comment by campersau** [comment]
@wmertens this is how you would only show the button on `mouseenter` / `mouseleave` but since the button is higher than the text it moves the files a bit down when it gets rendered. So for simplicity I am going to always show the button.
https://github.com/FredrikNoren/ungit/commit/4530d032839c868ff009abb8b603f670eb0e6879

**Pull request merged**
