### PR TITLE
Force git lang to english for ungit

### LINKED ISSUE #959: Don't auto-apply stash when switching branches
I may get something wrong here, but it is not clear to me why ungit automatically applies the stash I created on one branch to another branch on checkout. At first, I thought I might have some customized setting triggering that behavior, but I could not find anything like that.

From my understanding of git (and what I use as workflow), the idea is that you can use ´git stash´ to save your uncommited changes on Branch A, checkout another branch B, do some work, get back to Branch A, apply the stash and find everything like it was the moment you left.

Maybe also relevant: If I don't have any stashes and change branches, ungit will throw an error, reporting that theres no stash available.

### PR DESCRIPTION
**Pull request by codingtwinky**
fixes #959

### CODE REVIEW

**Comment by campersau** [comment]
Maybe you can try `LANG=en_US.UTF-8 && git`?
On windows the syntax will be: `set LANG=en_US.UTF-8 && git`
But I haven't tested it because I use english git.

**Comment by codingtwinky** [comment]
On  second thought, this is actually more complicated than my original thought.  I think even in different linux versions language specification is handled differently and it is not always guaranteed. 

Not to mention I can't even test this in Windows machine.

I would need more thought around this but for now we would have to simply document this.

**Comment by campersau** [comment]
Just for reference: ungit already sets the env variables here https://github.com/FredrikNoren/ungit/blob/master/bin/ungit#L20

See also:
https://github.com/FredrikNoren/ungit/pull/694
https://github.com/FredrikNoren/ungit/issues/676
https://github.com/FredrikNoren/ungit/issues/176

**Comment by codingtwinky** [comment]
So I've saw that and read some doc on node child process but this means that that env variable is not working.  If it was applied as one would have thought we wouldn't have #959 issue to begin with.

It is possible to add `LC_ALL`, `LANG` or any other keys but for whatever reason I couldn't successfully change git lang in my mac book and thus I couldn't really validate the fixes.

**Pull request closed without merging**
