### PR TITLE
Atom ungit fix

### PR DESCRIPTION
**Pull request by codingtwinky**
For: https://github.com/codingtwinky/atom-ungit/issues/21

Separated out refresh button as a component.

(Okay, maybe I'm going to far with extracting very small part to components, but no duplicate codes!)

### CODE REVIEW

**Comment by FredrikNoren** [comment]
Cool!

**Comment by FredrikNoren** [comment]
@codingtwinky hm somehow this broke the build, looks like clicktests are failing. looking at it right now

**Comment by FredrikNoren** [comment]
@codingtwinky uhm nvm, I re-ran it and it worked

**Comment by codingtwinky** [comment]
Before it was wiped away, I think I saw that it was for git submodule add.  Which has been bothering me since repo is trying to add it self as a submodule to self.

I may try to fix the clicktest later to add either cloned, or create another dummy git repo for this test.

**Comment by FredrikNoren** [comment]
@codingtwinky ok odd, I guess we'll find out if it's a regular thing

**Pull request merged**
