### PR TITLE
Bump dependencies including forever-monitor

### PR DESCRIPTION
**Pull request by codingtwinky**
* bump dep
* add sleep in nmclick test as op is going through too fast in nightmare
* remove forever monitor version lock down

cc: #961 @TitaneBoy

### CODE REVIEW

**Comment by campersau** [comment]
Sadly the cmd windows are poping up again on windows...

**Comment by campersau** [comment]
See https://github.com/foreverjs/forever-monitor/issues/147 if I comment out this line it works...

**Comment by codingtwinky** [comment]
I'm beginning to think that we should just drop forever monitor...  Have process die and let it be spawned if needed be considering ungit isn't mission critical process that needs high availability

**Comment by campersau** [comment]
We can update forever-monitor up to 1.2.4 which is the last version without the cmd windows bug. (1.3.0 and higher are affected.)
As @TitaneBoy already mentioned it will then work with [node >= 0.8.x](https://github.com/foreverjs/forever-monitor/blob/v1.2.4/package.json#L40)
I have successfully tested it on windows.

**Comment by TitaneBoy** [comment]
@campersau Great... Thank you for your help and support... One last question if possible: Does the fix is yet published in npm ? Because as I can see, the last release of ungit is since 3 weeks ..

Thanks :-)

**Comment by campersau** [comment]
@codingtwinky also update `package-lock.json`.

@TitaneBoy No, it is not published. We will close your issue #961 once it is fixed.

**Comment by campersau** [comment]
**Sorry** I have found another bug with forever-monitor 1.2.x which means we are stuck with 1.1.0...

After the 1.1.0 release they tried to be very clever by [allowing "complex" commands](https://github.com/foreverjs/forever-monitor/commit/d4a35488a679e146d0d22c577f7bf1b2dfc42a35#diff-8281e414f02aa1e5596b72f556bd4221R224). As you can see they are splitting the command by spaces to separate the executable from the args. But this also means that if the path to the executable (in our case nodejs) contains spaces the path will be broken.
E.g.: `C:\Program Files\nodejs\node.exe` becomes `C:\Program` `Files\nodejs\node.exe`

So running `bin/ungit` will not work because of the invalid executable path.

Maybe @codingtwinky is right by just dropping it. <sub>Or we can fork it...</sub>

---

forever-monitor versions:
- 1.1.0: works but is [restricted to node 0.8.x](https://github.com/foreverjs/forever-monitor/blob/ff6ff22cfefb56607a506e2b2c924a5cbdf4b41b/package.json#L40)
- 1.2.x: is not restricted to node 0.8.x but will not work with nodejs paths which include spaces
- 1.3.x and higher: does not really work on windows because [cmd windows are detached](https://github.com/foreverjs/forever-monitor/issues/147)

😢

**Comment by codingtwinky** [comment]
@campersau I'm going to downgrade it to 1.1.0 for now and I might send a different PR to remove forever monitor.

**Pull request merged**
