### PR TITLE
git 2.6.0 does not allow hunk with no change

### PR DESCRIPTION
**Pull request by linquize**
git 2.6.0 does not allow hunk with no change

Fix test failures.

### CODE REVIEW

**Comment by codingtwinky** [comment]
According to [migration guide for travis container](http://docs.travis-ci.com/user/migrating-from-legacy/), it seems that there is no way to allow `sudo` in travis container.  I guess it's something we would have to keep our eyes out for.

**Comment by linquize** [comment]
Since a build matrix is added (that `apt-get install git`), I have to use traditional VM, not container-based.

**Comment by codingtwinky** [comment]
you are absolutely right, I'm hoping travis would change to allow sudo in containers in near future.

**Comment by linquize** [comment]
Travis `sudo` attribute name is strange. If you need to use sudo, it will give you a VM. If not needed, it will give you a container.

**Pull request merged**
