### PR TITLE
Handle revert merge

### PR DESCRIPTION
**Pull request by codingtwinky**
fixes: #753 

To be honest, I really don't like this one.  one should be able to choose either 1st parent or 2nd parent but this one is hardcoded to parent1.  which is not ideal.  

I almost want to recommend users to moving the ref point instead of reverting.  How do you guys feel?  

(Upon confirmation I will add tests, and change log edit)

cc: @FredrikNoren @Ajedi32 @campersau

### CODE REVIEW

**Comment by Ajedi32** [comment]
`git revert` isn't the same thing as moving the ref point. In particular, there's a whole bunch of situations where the later isn't a good idea, like when others have work based off of the branch you're reverting. I think it makes sense to support both workflows.

Yeah, ideally there should be some way to select the mainline parent for the revert. The first parent _is_ probably going to be the correct choice ~75% of the time though (my totally unsubstantiated guess).

You could maybe improve that to like ~90% by guessing the parent based on the commit message used for the merge commit. E.g. Use the second parent instead of the first if the reverted commit's message says `Merge branch 'master' into feature` instead of the other way around and you're currently on the master branch.

**Comment by codingtwinky** [comment]
Right, I understand the difference between git revert and the moving the ref point.  But what I'm trying to say is that end result will be same and it's operation is much easier in ungit UI.  (Moving ref backward is a destructive op so perhaps it isn't "nice" either)

I may think on this more but I probably implement it as it is and maybe improve it later...

**Comment by Ajedi32** [comment]
The end result isn't the same. Especially if you have extra commits after the one you're trying to revert.

If you have:

```
a - b - c - d
```

And run `git revert c`, the end result will look like this:

```
a - b - c - d - e
```

And the working directory will still have the changes from d.

Whereas if you run `git reset --hard b`, the end result will look like this:

```
a - b
```

And the working directory will (obviously) not contain the changes from `c` or `d`.

> I may think on this more but I probably implement it as it is and maybe improve it later...

Yeah, being able to revert merge commits, even if only in a rather limited way, is a definite improvement over not being able to revert them at all.

**Comment by codingtwinky** [comment]
Git [2.9.0](https://github.com/blog/2188-git-2-9-has-been-released) is released and it seems that it is breaking the "git edge" build.  

This is supper annoying...

**Pull request merged**
