### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codingtwinky**
preview: https://github.com/codingtwinky/ungit/blob/readme/README.md

### CODE REVIEW

**Comment by campersau** [comment]
I think you forgot to add the [`xkcd.png`](https://github.com/codingtwinky/ungit/blob/readme/xkcd.png) in this PR. See https://github.com/codingtwinky/ungit/commit/7eecbb8d75a6ad4cb889827ad78eb0af994ddcf5

**Comment by campersau** [comment]
Ah never mind you already committed it without a PR: https://github.com/FredrikNoren/ungit/commit/7eecbb8d75a6ad4cb889827ad78eb0af994ddcf5

**Comment by codingtwinky** [comment]
Yea, so I have accidently pushed to remote rather then origin...  

(╯°□°）╯︵ ┻━┻

**Comment by FredrikNoren** [comment]
:joy:

**Pull request merged**
