### PR TITLE
Added windows shortcut

### PR DESCRIPTION
**Pull request by internetimagery**
To further abstract from the command line. This shortcut uses windows built in environment variables to open ungit in whatever directory the shortcut is clicked. Nifty to copy into a project for people who don't want to touch cmd. :)

### CODE REVIEW

**Comment by campersau** [comment]
I think the file can be named`ungit.lnk`. What do you think?

**Comment by Ajedi32** [comment]
Have you tested this to make sure it works for people other than you? I'm not on Windows right now, but inspecting the link file in a text editor I did see `\\HP-ZBOOK\Users\00maczone\AppData\Roaming\npm\ungit.cmd`, which seems likely to be specific to your setup.

**Comment by internetimagery** [comment]
Yeah it can be named anything. Also it could have an ungit icon added I assume (I believe icons are baked into the file?)

Yeah I've tested it on a couple computers. Been installing ungit on some animators computers I'm collaborating with, who are less technical.  :)
Windows is weird... I see what you mean. But after opening it in an editor as well and scrolling forever I can see that path you mentioned, and also the unresolved path is there:

C:\Users\%USERNAME%\AppData\Roaming\npm\ungit.cmd

Is it there for you? Had me worried. :palm_tree:

**Comment by Ajedi32** [comment]
Yeah, the unresolved path is also present. Like I said, I'm not on Windows, so I can't really test the shortcut myself, but as long as you've tested it on other computers I think it should be fine.

**Comment by Ajedi32** [comment]
Also related: #593 (Both these issues make using Ungit easier for non technical users.)

**Comment by codingtwinky** [comment]
I don't know how I feel about this.  isn't it arguable that end goal of #593 and this pr same?  I would vote for #593 as it will be OS independent, especially if #593 prevent us from having binary file being checked into git repo.

Hopefully pr for #593 come soon.

**Comment by codingtwinky** [comment]
Closing in favor of #610

**Pull request closed without merging**
