### PR TITLE
Enable es6

### PR DESCRIPTION
**Pull request by codingtwinky**
Simply enables es6 compilation for selective serverside codes.

updated: 16/1/21

* server side codes in `.../source` get compiled into `.../src` via babel dynamically based on the node env's es6 compatibility.
* coverage job uses compiled `.../src`
* For electron, `.../source` will be compiled with static preset with [es2015](https://babeljs.io/docs/plugins/preset-es2015/) and [stage-0](https://babeljs.io/docs/plugins/preset-stage-0/).  (which I think is conservative enough...)
* `.../source/utils/*`, `.../source/bugtracker.js` and `.../source/config.js` are refactored with es6 as an experiment.

It maybe a good idea to merge this after [ungit@1.0.0](https://github.com/FredrikNoren/ungit/issues/621) release.

### CODE REVIEW

**Comment by codingtwinky** [comment]
So it seems that this will kill node 0.10 and 0.12 is not liking es6 syntax as expected.

Are we okay with dropping the support for this?  I know node is dropping support for 0.10 soon but I'm not sure on the time line of 0.12.

**Comment by Ajedi32** [comment]
@codingtwinky Here's the timeline: https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png 0.12.x support will be dropped in December.

And yeah, like I said in #669, not all ES6 features are supported by Node yet. Even Node 5 is still missing support for some features: https://kangax.github.io/compat-table/es6/#node5

If you want full ES6 compatibility, definitely go with Babel.

**Comment by codingtwinky** [comment]
It was my intention to use raw es6 on the server side without babel as it does have some nice performance efficiency and drop support for some of the older ones. 

Is that too aggressive?

**Comment by Ajedi32** [comment]
I personally have no problem with dropping Node 0.10 and 0.12 support. Though I imagine that might cause minor headaches for some users who will need to upgrade to a newer node in order to keep using ungit.

If performance is your concern, one possibility is to just use the new native ES6 features in your code, then use Babel to degrade gracefully on older node versions. You could use [`babel-features`](https://github.com/hax/babel-features) to detect what features you're using aren't available on the current Node version, and automatically compile those features at runtime with [`babel-register`](https://babeljs.io/docs/usage/require/).

**Comment by codingtwinky** [comment]
That is so cool!  I didn't know about that babel could do that!  I will be experimenting with those features.

**Comment by codingtwinky** [comment]
it is ready for review.  As this changes A LOT, I would love to get your thoughts and blessings...  

cc: @FredrikNoren

**Comment by FredrikNoren** [comment]
@codingtwinky Looks reasonable to me, guess this just enables us to write es6 classes (in the backend only?) but only changes one class to use es6? The one thing: Do we really need to babel stuff? Or could we just drop support for old nodejs versions instead?

**Comment by codingtwinky** [comment]
@FredrikNoren You are correct, but converted classes are more than just one: `.../source/utils/*`, `.../source/bugtracker.js` and `.../source/config.js` as a trial.  Once this get merged in, we need to slowly convert serverside codes to use es6.

Yes, it maybe adding too much dependencies of Babel plugins and etc now that I'm looking back, which is [terrifying](https://github.com/azer/left-pad/issues/4).  I'm all for dropping support for old node and not doing this dynamic es6 compatibility checked compilation.  I can change it so that it is compiled using Babel with most conservative setting that will work in even the environments without any ES6 support (which I'd imagine we would have to do for client side).  That will allow us to drop most of the babel plugins dependencies.

FYI, here is the terrifying list of `npm list | grep babel` as of now.
```
├─┬ babel-preset-es2015@6.3.13
│ ├─┬ babel-plugin-check-es2015-constants@6.5.0
│ │ └─┬ babel-runtime@5.8.35
│ ├── babel-plugin-transform-es2015-arrow-functions@6.5.2
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.5.0
│ ├─┬ babel-plugin-transform-es2015-block-scoping@6.5.0
│ │ ├─┬ babel-template@6.5.0
│ │ ├─┬ babel-traverse@6.5.0
│ │ ├─┬ babel-types@6.5.2
│ ├─┬ babel-plugin-transform-es2015-classes@6.5.2
│ │ ├─┬ babel-helper-define-map@6.5.0
│ │ ├── babel-helper-function-name@6.5.0
│ │ ├── babel-helper-optimise-call-expression@6.5.0
│ │ ├── babel-helper-replace-supers@6.5.0
│ │ └── babel-messages@6.5.0
│ ├── babel-plugin-transform-es2015-computed-properties@6.5.2
│ ├── babel-plugin-transform-es2015-destructuring@6.5.0
│ ├── babel-plugin-transform-es2015-for-of@6.5.2
│ ├── babel-plugin-transform-es2015-function-name@6.5.0
│ ├── babel-plugin-transform-es2015-literals@6.5.0
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.5.2
│ │ └── babel-plugin-transform-strict-mode@6.5.2
│ ├── babel-plugin-transform-es2015-object-super@6.5.0
│ ├─┬ babel-plugin-transform-es2015-parameters@6.5.0
│ │ ├── babel-helper-call-delegate@6.5.0
│ │ └── babel-helper-get-function-arity@6.5.0
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.5.0
│ ├── babel-plugin-transform-es2015-spread@6.5.2
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.5.0
│ │ └─┬ babel-helper-regex@6.5.0
│ ├── babel-plugin-transform-es2015-template-literals@6.5.2
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.5.0
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.5.0
│ └─┬ babel-plugin-transform-regenerator@6.5.2
│   ├── babel-plugin-syntax-async-functions@6.5.0
├─┬ babel-preset-features@2.0.5
│ ├── babel-features@2.0.0-beta
│ ├── babel-plugin-jscript@1.0.4
│ ├─┬ babel-plugin-transform-async-to-generator@6.5.0
│ │ └── babel-helper-remap-async-to-generator@6.5.0
│ ├── babel-plugin-transform-es2015-constants@6.1.4
│ ├── babel-plugin-transform-es2015-modules-amd@6.5.0
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.5.0
│ │ └── babel-helper-hoist-variables@6.5.0
│ ├── babel-plugin-transform-es2015-modules-umd@6.5.0
│ ├── babel-plugin-transform-es3-member-expression-literals@6.5.0
│ ├── babel-plugin-transform-es3-property-literals@6.5.0
│ ├── babel-plugin-transform-es5-property-mutators@6.5.0
│ └── babel-plugin-transform-jscript@6.5.0
├─┬ babel-preset-stage-0@6.3.13
│ ├─┬ babel-plugin-transform-do-expressions@6.5.0
│ │ └── babel-plugin-syntax-do-expressions@6.5.0
│ ├─┬ babel-plugin-transform-function-bind@6.5.2
│ │ └── babel-plugin-syntax-function-bind@6.5.0
│ └─┬ babel-preset-stage-1@6.5.0
│   ├─┬ babel-plugin-transform-class-constructor-call@6.5.0
│   │ └── babel-plugin-syntax-class-constructor-call@6.5.0
│   ├─┬ babel-plugin-transform-class-properties@6.5.2
│   │ └── babel-plugin-syntax-class-properties@6.5.0
│   ├─┬ babel-plugin-transform-decorators@6.5.0
│   │ ├─┬ babel-helper-explode-class@6.5.0
│   │ │ └── babel-helper-bindify-decorators@6.5.0
│   │ └── babel-plugin-syntax-decorators@6.5.0
│   ├─┬ babel-plugin-transform-export-extensions@6.5.0
│   │ └── babel-plugin-syntax-export-extensions@6.5.0
│   └─┬ babel-preset-stage-2@6.5.0
│     ├── babel-plugin-syntax-trailing-function-commas@6.5.0
│     ├─┬ babel-plugin-transform-object-rest-spread@6.5.0
│     │ └── babel-plugin-syntax-object-rest-spread@6.5.0
│     └─┬ babel-preset-stage-3@6.5.0
│       └─┬ babel-plugin-transform-exponentiation-operator@6.5.0
│         ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.5.0
│         │ └── babel-helper-explode-assignable-expression@6.5.0
│         └── babel-plugin-syntax-exponentiation-operator@6.5.0
├─┬ grunt-babel@6.0.0
│ └─┬ babel-core@6.5.2
│   ├─┬ babel-code-frame@6.5.0
│   ├─┬ babel-generator@6.5.0
│   ├── babel-helpers@6.5.0
│   ├─┬ babel-register@6.5.2

```

**Comment by Ajedi32** [comment]
Yeah, usually Babel is only used in development, and the compiled files are used in production.

I know you were concerned about the performance costs of transpiled Babel code, but in all honesty I kinda suspect that doing the transpilation on the fly would actually be slower than just using transpiled code (even for features natively supported in newer node versions).

I still think Babel is still probably a good idea, because for some of the newer ES6 features even the latest versions of Node don't support them natively, but it's probably best to just do the transpilation in development.

**Comment by FredrikNoren** [comment]
@codingtwinky Ah I see, yeah if we're transpiling we should probably just do it before uploading to npm (i.e. what @Ajedi32 said), I guess there's not much downside to running the transpiled code everywhere (except the maybe performance but I don't think we need to worry)?

Generally anything that makes the installation process flakier I would advice against, since I see so much people having trouble with the installation. Anything that can fail we should remove.

**Comment by codingtwinky** [comment]
I agree with those wise words.

I will remove this dynamic environment dependent babel transpiling, although I think it's supa cewl I agree that it is bit risky and not worth it.

**Comment by codingtwinky** [comment]
@FredrikNoren @Ajedi32 @campersau 

Now grunt job statically uses `['es2015', 'stage-0']` presets which is conservative to for all node versions and it should work for client side as well when we begin using babel for clientside.

**Comment by campersau** [comment]
:+1:

**Comment by codingtwinky** [comment]
Merging it for now but please do post any and all comment so we can fix in other PRs.

**Pull request merged**
