### PR TITLE
Prepare version 1.5.7

### PR DESCRIPTION
**Pull request by campersau**
### Fixed
- Init tooltips from the app start [#1343](https://github.com/FredrikNoren/ungit/pull/1343)
- Fixing some accessibility issues [#1318](https://github.com/FredrikNoren/ungit/pull/1318)
- Flatten total-lines-changed object [#1330](https://github.com/FredrikNoren/ungit/pull/1330)
- Set electron window icon explicitly so it works during debug and on linux [#1347](https://github.com/FredrikNoren/ungit/pull/1347)

### Changed
- Only display ref search button when there are hidden refs [#1311](https://github.com/FredrikNoren/ungit/pull/1311), [#1325](https://github.com/FredrikNoren/ungit/pull/1325)
- Cleanup CSS styles [#1339](https://github.com/FredrikNoren/ungit/pull/1339), [#1328](https://github.com/FredrikNoren/ungit/pull/1328), [#1331](https://github.com/FredrikNoren/ungit/pull/1331), [#1332](https://github.com/FredrikNoren/ungit/pull/1332), [#1322](https://github.com/FredrikNoren/ungit/pull/1322)
- Style autocompletes like dropdowns [#1327](https://github.com/FredrikNoren/ungit/pull/1327)
- Optimizes ref-search autocomplete initialization [#1326](https://github.com/FredrikNoren/ungit/pull/1326)
- Reduce jQuery UI imports and use Bootstrap tooltips [#1340](https://github.com/FredrikNoren/ungit/pull/1340)
- Image cleanup [#1345](https://github.com/FredrikNoren/ungit/pull/1345)
- Bump Dependencies [#1309](https://github.com/FredrikNoren/ungit/pull/1309)

### Removed
- Remove unused color dependency [#1341](https://github.com/FredrikNoren/ungit/pull/1341)
- Remove image embed [#1346](https://github.com/FredrikNoren/ungit/pull/1346)
- Remove unused tracker.js [#1344](https://github.com/FredrikNoren/ungit/pull/1344)

---

Thanks @Hirse, @ylecuyer, @bakkerthehacker, @jung-kim !

Here is my current plan:
- Did I miss something in the changelog?
- @Hirse do you want to update the electron app icon in #1345 or is it ready to merge?
- Bump dependencies #1309 when jQuery 3.5.1 is available (should be in a few hours)
- Release this version
- Migrate clicktests to puppeteer #1336 so we can use more Promise features on the client
- Get rid of Bluebird and use native promises (I have already made these changes here  https://github.com/FredrikNoren/ungit/compare/master...campersau:bluebird)
- Use prettier #1316 by @wmertens

### CODE REVIEW

**Comment by wmertens** [comment]
Regarding the Promise move:
* How about rewriting the promises to async/await, with the help of https://github.com/sgilroy/async-await-codemod?
* The `fs` module promisifications could be provided by https://www.npmjs.com/package/fs-extra, which also adds some convenience methods and workarounds for Windows behavior

**Comment by Hirse** [comment]
@campersau the list looks good to me.

I'll update the icons in #1345. Do you remember what service you used to create the icns file?

**Comment by Hirse** [comment]
@wmertens Is the first link a tool to migrate the code? I think the codebase is small enough to handle it manually.

Secondly, since node 10, node has a native [fs Promises API](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api): `fs.promises`

**Comment by wmertens** [comment]
@Hirse indeed, an automated tool, and it's much faster than doing it manually. The idea is to run it and then verify.

I always grab fs-extra for the helpers, but indeed in this case the fs.promises are sufficient

**Comment by campersau** [comment]
Yes, in **addition** to moving to native promises we can also refactor the code to use async / await afterwards. I actually had that as the last point after prettier but removed it because I hadn't checked browser support at that time.
Using the tool @wmertens mentioned is a good start but we definitely have to check the code manually because we currently use some syntax which I also want to get rid of like https://github.com/FredrikNoren/ungit/pull/1336#discussion_r416767859

Thanks @Hirse for the `fs.promises` hint, I had used [`util.promisify(fs.api)`](https://github.com/FredrikNoren/ungit/compare/master...campersau:bluebird#diff-35b4a816e0441e6a375cd925af50752cR10) in my bluebird removal branch andI will replace that before I create the PR.

**Pull request merged**
